#!/usr/bin/with-contenv bash

mkdir -p /webui /mnt
chmod +x /config/trackers-list-update.sh
/config/trackers-list-update.sh 2>&1

# copy

[[ ! -f /config/aria2.conf ]] && cp /defaults/aria2.conf /config/aria2.conf

[[ ! -f /config/aria2.session ]] && touch /config/aria2.session

# permissions
chown abc:abc -R \
	/mnt
