#!/usr/bin/with-contenv bash

mkdir -p /webui /mnt
chmod +x /defaults/trackers-list-update.sh

# copy

[[ ! -f /config/aria2.conf ]] && cp /defaults/aria2.conf /config/aria2.conf

[[ ! -f /config/aria2.session ]] && touch /config/aria2.session

[[ ! -f /config/dht.dat ]] && touch /config/dht.dat

[[ ! -f /config/dht6.dat ]] && touch /config/dht6.dat

chown abc:abc /config/aria2.conf /config/aria2.session /config/dht.dat /config/dht6.dat

# add tracker
tmp=`curl -s https://trackerslist.com/best.txt`
list=`echo $tmp | sed 's/[ ][ ]*/,/g'`
if [ -z "`grep "bt-tracker" /config/aria2.conf`" ]; then
    sed -i '$a bt-tracker='${list} /config/aria2.conf
    echo add tracker ...
else
    sed -i "s@bt-tracker.*@bt-tracker=$list@g" /config/aria2.conf
    echo update tracker ...
fi

# permissions
chown abc:abc -R \
	/mnt \
	/config
